const translations = {
  en: {
    documentTitle: "Dingshuai Yang | Robotics, Control, AI",
    metaDescription:
      "Dingshuai Yang's multilingual personal website for robotics, control engineering, mechatronics, AI, and automation projects.",
    homeAria: "Back to homepage",
    languageAria: "Language selection",
    actionsAria: "Primary actions",
    profileAria: "Personal information summary",
    brandMark: "DY",
    brandName: "Dingshuai Yang",
    navAbout: "About",
    navEducation: "Education",
    navSkills: "Skills",
    navProjects: "Labs",
    navContact: "Contact",
    introLine: "Personal website",
    heroGreeting: "Hi, I am",
    heroName: "Dingshuai Yang",
    heroDomain1: "Robotics",
    heroDomain2: "Control Engineering",
    heroDomain3: "AI",
    heroTitle: "Hi, I am Dingshuai Yang. I work across robotics, control engineering, and AI.",
    heroText:
      "Currently in Erlangen for a masters in mechatronics. Most of my time goes into control loops, manipulators, and the AI tools that make them smarter.",
    viewProjects: "View labs →",
    contactMe: "Contact me",
    profileTitle: "M.Sc. Mechatronics  ·  2025 – 2027  ·  FAU",
    profileRole: "Friedrich-Alexander University Erlangen-Nürnberg (FAU) · Erlangen, Germany",
    focusLabel: "Focus",
    focusValue: "Robotics, Control Engineering, Computer Science, AI & LLMs",
    statusLabel: "Currently learning",
    statusValue: "Computer Science fundamentals, AI, Machine Learning, LLMs, and Prompt Engineering",
    aboutLabel: "About me",
    aboutTitle: "From materials engineering to mechatronics, robotics, and AI.",
    aboutText1:
      "I started in materials engineering, but my real curiosity has always been the machines themselves — and the question of what makes them intelligent. Watching humanoid robots learn to walk, manipulate, and reason is what pulled me into this field.",
    aboutQuote: "I believe humanoid robots and embodied intelligence are the future.",
    aboutText2:
      "So I switched to mechatronics and moved to Erlangen — to learn the control loops, the manipulators, and the AI tools that will, sooner or later, walk through every kitchen and every factory floor.",
    educationLabel: "Education",
    educationTitle: "Where I have studied.",
    edu1Degree: "M.Sc. Mechatronics",
    edu1School: "Friedrich-Alexander University Erlangen-Nürnberg (FAU) · Erlangen, Germany",
    edu1Status: "In progress",
    edu2Degree: "B.Eng. Materials Processing & Controlling Engineering",
    edu2School: "Guangdong University of Technology (GDUT) · Guangzhou, China",
    skillsLabel: "Skills",
    skillsTitle: "A practical stack across control, robot software, and AI tools.",
    skillCat1: "Languages",
    skillCat2: "Robotics & Sim",
    factLocLabel: "Based in",
    factLocValue: "Erlangen, Germany",
    factGradLabel: "Graduating",
    factGradValue: "April 2027",
    factOpenLabel: "Open to",
    factOpenValue: "Internships · working-student roles in robotics, control, AI",
    skillCat4: "ML & AI",
    skillCat5: "Dev Tools",
    skillCat3: "Domains",
    nowLabel: "Now",
    nowText: "Studying Computer Science fundamentals, AI, Machine Learning, LLMs, and Prompt Engineering. Building personal projects in AI and automation.",
    skill1Title: "Robotics & Control",
    skill1Text: "ROS/ROS2, MATLAB, Simulink, OpenCV, control systems, and robot simulation.",
    skill2Title: "Programming & Systems",
    skill2Text: "Python, C++, Linux, GitHub, data processing, and engineering scripts.",
    skill3Title: "AI & Automation",
    skill3Text: "AI, Machine Learning, PyTorch, LLMs, Prompt Engineering, and automation projects.",
    languagesLabel: "Languages",
    languagesTitle: "Languages I speak.",
    lang1Name: "Chinese",
    lang1Level: "Native",
    lang2Name: "German",
    lang2Level: "C1",
    lang3Name: "English",
    lang3Level: "B2",
    lang4Name: "Japanese",
    lang4Level: "≈ N4",
    projectsLabel: "Labs & Experiments",
    projectsTitle: "Coursework and self-built experiments.",
    demo1Title: "Pendulum-Cart Visualizer",
    demo1Meta: "Interactive demo  ·  2025",
    demo1Text: "An in-browser interactive simulation of an inverted pendulum on a cart. Tunable mass, length, damping, and live state plotting.",
    demo2Title: "Planar 2R Robot Simulator",
    demo2Meta: "Interactive demo  ·  2025",
    demo2Text: "Two-link planar manipulator: drag the end-effector to explore forward and inverse kinematics.",
    demo3Title: "7-DOF Robot Arm Simulator",
    demo3Meta: "Interactive demo  ·  2025",
    demo3Text: "A 7-degree-of-freedom robotic arm in the browser. Joint-by-joint control with DH-based modelling.",
    demo5Title: "RRT — Rapidly-exploring Random Tree",
    demo5Meta: "Python source  ·  2025",
    demo5Text: "Single-tree sampling-based planner. Animated tree growth with obstacle avoidance, written in Python with tkinter.",
    demo6Title: "Bidirectional RRT",
    demo6Meta: "Python source  ·  2025",
    demo6Text: "Two trees grow simultaneously from start and goal; the planner stitches them together once they meet. Live animation in tkinter.",
    demo7Title: "PRM — Probabilistic Roadmap",
    demo7Meta: "Python source  ·  2025",
    demo7Text: "Random sampling builds a connectivity graph in free space; Dijkstra finds the shortest collision-free path. Ideal for multi-query static scenes.",
    project1Title: "MATLAB Laboratory Course",
    project1Timeline: "Course lab  ·  WS 2025/26",
    project1Text:
      "Content: Static truss, Dynamic Crane, Measurement Data Analysis, and truss structure optimisation. The lab used MATLAB for structural mechanics modeling, ODE simulation, FFT signal analysis, symbolic computation, and optimisation tasks.",
    project2Title: "Automatic Control I Lab / Regelungstechnik I",
    project2Timeline: "Course lab  ·  SS 2026",
    project2Text:
      "Content: lab stations include Two Tank System, MATLAB 1, MATLAB 2, Rotary Arm, Active Suspension, and Magnetic Levitation System. The lab applies fundamentals from Regelungstechnik A / dynamical systems and control to modeling, simulation, controller design, and experimental observation.",
    contactLabel: "Contact me",
    followLabel: "Follow me",
    contactTitle: "Ask me about robotics, control systems, AI tools, and LLMs.",
    footerText: "© 2026 Dingshuai Yang.",
    footerSource: "Source ↗",
    footerUpdated: "Updated 2026-05-26",
    backToTop: "Back to top"
  },
  de: {
    documentTitle: "Dingshuai Yang | Robotik, Regelungstechnik, KI",
    metaDescription:
      "Mehrsprachige persönliche Website von Dingshuai Yang für Robotik, Regelungstechnik, Mechatronik, KI und Automatisierungsprojekte.",
    homeAria: "Zur Startseite",
    languageAria: "Sprachauswahl",
    actionsAria: "Hauptaktionen",
    profileAria: "Zusammenfassung persönlicher Informationen",
    brandMark: "DY",
    brandName: "Dingshuai Yang",
    navAbout: "Über mich",
    navEducation: "Ausbildung",
    navSkills: "Fähigkeiten",
    navProjects: "Labore",
    navContact: "Kontakt",
    introLine: "Persönliche Website",
    heroGreeting: "Hallo, ich bin",
    heroName: "Dingshuai Yang",
    heroDomain1: "Robotik",
    heroDomain2: "Regelungstechnik",
    heroDomain3: "KI",
    heroTitle: "Hallo, ich bin Dingshuai Yang. Ich arbeite an Robotik, Regelungstechnik und KI.",
    heroText:
      "Aktuell in Erlangen für den Master in Mechatronik. Die meiste Zeit fließt in Regelkreise, Manipulatoren und die KI-Tools, die sie schlauer machen.",
    viewProjects: "Labore ansehen →",
    contactMe: "Kontakt aufnehmen",
    profileTitle: "M.Sc. Mechatronik  ·  2025 – 2027  ·  FAU",
    profileRole: "Friedrich-Alexander-Universität Erlangen-Nürnberg (FAU) · Erlangen, Germany",
    focusLabel: "Schwerpunkt",
    focusValue: "Robotik, Regelungstechnik, Informatik, KI & LLMs",
    statusLabel: "Derzeit lerne ich",
    statusValue: "Grundlagen der Informatik, KI, Machine Learning, LLMs und Prompt Engineering",
    aboutLabel: "Über mich",
    aboutTitle: "Von Materialwissenschaften über Mechatronik bis hin zu Robotik und KI.",
    aboutText1:
      "Ich habe im Materialingenieurwesen angefangen, aber meine eigentliche Neugier galt schon immer den Maschinen selbst — und der Frage, was sie intelligent macht. Wenn humanoide Roboter lernen, zu gehen, zu greifen und zu schlussfolgern, ist das für mich der Grund, warum ich in dieses Feld eingestiegen bin.",
    aboutQuote: "Ich glaube, humanoide Roboter und Embodied Intelligence sind die Zukunft.",
    aboutText2:
      "Deshalb bin ich zur Mechatronik gewechselt und nach Erlangen gezogen — um die Regelkreise, Manipulatoren und KI-Werkzeuge zu lernen, die früher oder später durch jede Küche und jede Fabrikhalle gehen werden.",
    educationLabel: "Ausbildung",
    educationTitle: "Wo ich studiert habe.",
    edu1Degree: "M.Sc. Mechatronik",
    edu1School: "Friedrich-Alexander-Universität Erlangen-Nürnberg (FAU) · Erlangen, Deutschland",
    edu1Status: "Laufend",
    edu2Degree: "B.Eng. Materialumformung & Steuerungstechnik",
    edu2School: "Guangdong University of Technology (GDUT) · Guangzhou, China",
    skillsLabel: "Fähigkeiten",
    skillsTitle: "Ein praxisnaher Stack für Regelung, Robotersoftware und KI-Tools.",
    skillCat1: "Sprachen",
    skillCat2: "Robotik & Sim",
    factLocLabel: "Standort",
    factLocValue: "Erlangen, Deutschland",
    factGradLabel: "Abschluss",
    factGradValue: "April 2027",
    factOpenLabel: "Offen für",
    factOpenValue: "Praktika · Werkstudentenstellen in Robotik, Regelung, KI",
    skillCat4: "ML & KI",
    skillCat5: "Dev Tools",
    skillCat3: "Bereiche",
    nowLabel: "Aktuell",
    nowText: "Lerne Computer-Science-Grundlagen, KI, Machine Learning, LLMs und Prompt Engineering. Baue persönliche Projekte in KI und Automatisierung.",
    skill1Title: "Robotik & Regelung",
    skill1Text: "ROS/ROS2, MATLAB, Simulink, OpenCV, Regelungssysteme und Robotersimulation.",
    skill2Title: "Programmierung & Systeme",
    skill2Text: "Python, C++, Linux, GitHub, Datenverarbeitung und Engineering-Skripte.",
    skill3Title: "KI & Automatisierung",
    skill3Text: "KI, Machine Learning, PyTorch, LLMs, Prompt Engineering und Automatisierungsprojekte.",
    languagesLabel: "Sprachen",
    languagesTitle: "Sprachen, die ich spreche.",
    lang1Name: "Chinesisch",
    lang1Level: "Muttersprache",
    lang2Name: "Deutsch",
    lang2Level: "C1",
    lang3Name: "Englisch",
    lang3Level: "B2",
    lang4Name: "Japanisch",
    lang4Level: "≈ N4",
    projectsLabel: "Labore & Experimente",
    projectsTitle: "Lehrlabore und eigene Experimente.",
    demo1Title: "Pendel-Wagen-Visualizer",
    demo1Meta: "Interaktive Demo  ·  2025",
    demo1Text: "Interaktive Simulation eines invertierten Pendels auf einem Wagen im Browser. Masse, Länge, Dämpfung einstellbar mit Live-Plot.",
    demo2Title: "Planarer 2R-Roboter Simulator",
    demo2Meta: "Interaktive Demo  ·  2025",
    demo2Text: "Zweigliedriger planarer Manipulator: End-Effektor ziehen, um Vorwärts- und Inverskinematik zu erkunden.",
    demo3Title: "7-DOF Roboterarm Simulator",
    demo3Meta: "Interaktive Demo  ·  2025",
    demo3Text: "Ein 7-Achsen-Roboterarm im Browser. Gelenkweise Steuerung mit DH-Parametern.",
    demo5Title: "RRT — Rapidly-exploring Random Tree",
    demo5Meta: "Python-Quellcode  ·  2025",
    demo5Text: "Sampling-basierter Planer mit einem Baum. Animierte Baumerweiterung mit Hinderniserkennung, in Python + tkinter.",
    demo6Title: "Bidirektionales RRT",
    demo6Meta: "Python-Quellcode  ·  2025",
    demo6Text: "Zwei Bäume wachsen gleichzeitig von Start und Ziel und werden beim Aufeinandertreffen zusammengeführt. Live-Animation in tkinter.",
    demo7Title: "PRM — Probabilistic Roadmap",
    demo7Meta: "Python-Quellcode  ·  2025",
    demo7Text: "Zufällige Stichproben bilden einen Graphen im freien Raum; Dijkstra findet den kürzesten kollisionsfreien Pfad. Geeignet für Mehrfachabfragen.",
    project1Title: "MATLAB Laboratory Course",
    project1Timeline: "Lehrlabor  ·  WS 2025/26",
    project1Text:
      "Inhalt: Static truss, Dynamic Crane, Measurement Data Analysis und Optimisation of the truss structure. Das Labor nutzte MATLAB für Strukturmechanik-Modellierung, ODE-Simulation, FFT-Signalanalyse, symbolische Berechnung und Optimierung.",
    project2Title: "Automatic Control I Lab / Regelungstechnik I",
    project2Timeline: "Lehrlabor  ·  SS 2026",
    project2Text:
      "Inhalt: Laborstationen sind Two Tank System, MATLAB 1, MATLAB 2, Rotary Arm, Active Suspension und Magnetic Levitation System. Das Labor wendet Grundlagen aus Regelungstechnik A / dynamical systems and control auf Modellierung, Simulation, Reglerentwurf und experimentelle Beobachtung an.",
    contactLabel: "Kontaktiere mich",
    followLabel: "Folge mir",
    contactTitle: "Sprich mich an über Robotik, Control Systems, KI-Tools und LLMs.",
    footerText: "© 2026 Dingshuai Yang.",
    footerSource: "Quellcode ↗",
    footerUpdated: "Aktualisiert 2026-05-26",
    backToTop: "Nach oben"
  },
  zh: {
    documentTitle: "杨定帅 | 机器人、控制工程、AI",
    metaDescription: "杨定帅的多语言个人主页，展示机器人、控制工程、机电一体化、AI 与自动化项目。",
    homeAria: "返回首页",
    languageAria: "语言选择",
    actionsAria: "主要操作",
    profileAria: "个人信息摘要",
    brandMark: "DY",
    brandName: "杨定帅",
    navAbout: "关于",
    navEducation: "教育",
    navSkills: "技能",
    navProjects: "实验",
    navContact: "联系",
    introLine: "个人主页",
    heroGreeting: "你好，我是",
    heroName: "杨定帅",
    heroDomain1: "机器人",
    heroDomain2: "控制工程",
    heroDomain3: "人工智能",
    heroTitle: "你好，我是杨定帅。这里展示我的机器人、控制工程与 AI 项目。",
    heroText:
      "现在在埃尔朗根读机电一体化硕士。大部分时间花在控制回路、机械臂、以及让它们更聪明的 AI 工具上。",
    viewProjects: "查看实验 →",
    contactMe: "联系我",
    profileTitle: "M.Sc. 机电一体化  ·  2025 – 2027  ·  FAU",
    profileRole: "Friedrich-Alexander-Universität Erlangen-Nürnberg (FAU) · Erlangen, Germany",
    focusLabel: "关注方向",
    focusValue: "Robotics、Control Engineering、Computer Science、AI & LLMs",
    statusLabel: "当前学习",
    statusValue: "Computer Science fundamentals、AI、Machine Learning、LLMs 与 Prompt Engineering",
    aboutLabel: "关于我",
    aboutTitle: "从材料工程到机电一体化，再到 Robotics 与 AI。",
    aboutText1:
      "我本科学的是材料工程，但真正让我好奇的从来是那些机器本身——以及让它们变得智能的那些东西。看着人形机器人学会走路、抓取、像人一样推理，是把我拉进这个领域的根本原因。",
    aboutQuote: "我相信人形机器人和具身智能就是未来。",
    aboutText2:
      "所以我转到机电一体化，跑到 Erlangen 读硕士——把控制回路、机械臂、和现代 AI 工具一个个学会。早晚它们会走进每个厨房和每条产线，我希望那时候我也在那里。",
    educationLabel: "教育经历",
    educationTitle: "我读过的学校。",
    edu1Degree: "M.Sc. 机电一体化",
    edu1School: "埃尔朗根-纽伦堡大学 (FAU) · 德国埃尔朗根",
    edu1Status: "在读",
    edu2Degree: "工学学士 · 材料成型及控制工程",
    edu2School: "广东工业大学 (GDUT) · 中国广州",
    skillsLabel: "技能",
    skillsTitle: "跨越控制、机器人软件与 AI 工具链。",
    skillCat1: "编程语言",
    skillCat2: "机器人与仿真",
    factLocLabel: "所在地",
    factLocValue: "德国 埃尔朗根",
    factGradLabel: "毕业时间",
    factGradValue: "2027 年 4 月",
    factOpenLabel: "目前在找",
    factOpenValue: "机器人 / 控制 / AI 方向的实习与 Werkstudent",
    skillCat4: "机器学习 / AI",
    skillCat5: "开发工具",
    skillCat3: "方向",
    nowLabel: "近期",
    nowText: "正在学习 Computer Science 基础、AI、Machine Learning、LLMs 与 Prompt Engineering。同时在做 AI 与自动化方向的个人项目。",
    skill1Title: "Robotics & Control",
    skill1Text: "ROS/ROS2、MATLAB、Simulink、OpenCV、控制系统与机器人仿真。",
    skill2Title: "Programming & Systems",
    skill2Text: "Python、C++、Linux、GitHub、数据处理与工程化脚本。",
    skill3Title: "AI & Automation",
    skill3Text: "AI、Machine Learning、PyTorch、LLMs、Prompt Engineering 与自动化项目。",
    languagesLabel: "语言",
    languagesTitle: "我会说的语言。",
    lang1Name: "中文",
    lang1Level: "母语",
    lang2Name: "德语",
    lang2Level: "C1",
    lang3Name: "英语",
    lang3Level: "B2",
    lang4Name: "日语",
    lang4Level: "≈ N4",
    projectsLabel: "实验与项目",
    projectsTitle: "课程实验与个人小项目。",
    demo1Title: "倒立摆-小车可视化",
    demo1Meta: "交互式 demo  ·  2025",
    demo1Text: "浏览器内可交互的倒立摆 + 小车系统仿真，可调质量、长度、阻尼等参数，实时观察状态变化与控制信号。",
    demo2Title: "平面 2R 机械臂仿真",
    demo2Meta: "交互式 demo  ·  2025",
    demo2Text: "二连杆平面机械臂仿真，可拖拽末端执行器，实时演示正向 / 逆向运动学解算。",
    demo3Title: "7 自由度机械臂仿真",
    demo3Meta: "交互式 demo  ·  2025",
    demo3Text: "浏览器中的 7 自由度机械臂可视化，可逐关节控制并观察末端姿态变化，基于 DH 参数建模。",
    demo5Title: "RRT — 快速扩展随机树",
    demo5Meta: "Python 源码  ·  2025",
    demo5Text: "基于随机采样的单向树路径规划，tkinter 实时动画展示树扩展与避障，可对比不同参数下的结果。",
    demo6Title: "Bidirectional RRT",
    demo6Meta: "Python 源码  ·  2025",
    demo6Text: "两棵采样树分别从起点与终点同时生长，相遇即得通路。可视化展示两树扩展过程与最终拼接路径。",
    demo7Title: "PRM — 概率路图",
    demo7Meta: "Python 源码  ·  2025",
    demo7Text: "对自由空间随机采样并构建近邻图，再用 Dijkstra 求最短无碰撞路径。适合多次查询的静态场景。",
    project1Title: "MATLAB Laboratory Course",
    project1Timeline: "课程实验  ·  WS 2025/26",
    project1Text:
      "内容：Static truss、Dynamic Crane、Measurement Data Analysis 和 Optimisation of the truss structure。实验使用 MATLAB 完成结构力学建模、ODE 仿真、FFT 信号分析、符号计算和优化任务。",
    project2Title: "Automatic Control I Lab / Regelungstechnik I",
    project2Timeline: "课程实验  ·  SS 2026",
    project2Text:
      "内容：实验站点包括 Two Tank System、MATLAB 1、MATLAB 2、Rotary Arm、Active Suspension 和 Magnetic Levitation System。课程实验围绕自动控制基础，将 Regelungstechnik A / dynamical systems and control 的理论用于建模、仿真、控制器设计和实验观察。",
    contactLabel: "联系我",
    followLabel: "关注我",
    contactTitle: "欢迎交流 Robotics、Control Systems、AI Tools 与 LLMs。",
    footerText: "© 2026 杨定帅.",
    footerSource: "源码 ↗",
    footerUpdated: "更新于 2026-05-26",
    backToTop: "回到顶部"
  },
  zhTw: {
    documentTitle: "楊定帥 | 機器人、控制工程、AI",
    metaDescription: "楊定帥的多語言個人主頁，展示機器人、控制工程、機電一體化、AI 與自動化項目。",
    homeAria: "返回首頁",
    languageAria: "語言選擇",
    actionsAria: "主要操作",
    profileAria: "個人信息摘要",
    brandMark: "DY",
    brandName: "楊定帥",
    navAbout: "關於",
    navEducation: "教育",
    navSkills: "技能",
    navProjects: "實驗",
    navContact: "聯繫",
    introLine: "個人主頁",
    heroGreeting: "你好，我是",
    heroName: "楊定帥",
    heroDomain1: "機器人",
    heroDomain2: "控制工程",
    heroDomain3: "人工智能",
    heroTitle: "你好，我是楊定帥。這裡展示我的機器人、控制工程與 AI 項目。",
    heroText:
      "現在在埃爾朗根讀機電一體化碩士。大部分時間花在控制迴路、機械臂、以及讓它們更聰明的 AI 工具上。",
    viewProjects: "查看實驗 →",
    contactMe: "聯繫我",
    profileTitle: "M.Sc. 機電一體化  ·  2025 – 2027  ·  FAU",
    profileRole: "Friedrich-Alexander-Universität Erlangen-Nürnberg (FAU) · Erlangen, Germany",
    focusLabel: "關注方向",
    focusValue: "Robotics、Control Engineering、Computer Science、AI & LLMs",
    statusLabel: "當前學習",
    statusValue: "Computer Science fundamentals、AI、Machine Learning、LLMs 與 Prompt Engineering",
    aboutLabel: "關於我",
    aboutTitle: "從材料工程到機電一體化，再到 Robotics 與 AI。",
    aboutText1:
      "我本科學的是材料工程，但真正讓我好奇的從來是那些機器本身——以及讓它們變得智能的那些東西。看著人形機器人學會走路、抓取、像人一樣推理，是把我拉進這個領域的根本原因。",
    aboutQuote: "我相信人形機器人和具身智能就是未來。",
    aboutText2:
      "所以我轉到機電一體化，跑到 Erlangen 讀碩士——把控制迴路、機械臂、和現代 AI 工具一個個學會。早晚它們會走進每個廚房和每條產線，我希望那時候我也在那裡。",
    educationLabel: "教育經歷",
    educationTitle: "我讀過的學校。",
    edu1Degree: "M.Sc. 機電一體化",
    edu1School: "埃爾朗根-紐倫堡大學 (FAU) · 德國埃爾朗根",
    edu1Status: "在讀",
    edu2Degree: "工學學士 · 材料成型及控制工程",
    edu2School: "廣東工業大學 (GDUT) · 中國廣州",
    skillsLabel: "技能",
    skillsTitle: "跨越控制、機器人軟件與 AI 工具鏈。",
    skillCat1: "編程語言",
    skillCat2: "機器人與仿真",
    factLocLabel: "所在地",
    factLocValue: "德國 埃爾朗根",
    factGradLabel: "畢業時間",
    factGradValue: "2027 年 4 月",
    factOpenLabel: "目前在找",
    factOpenValue: "機器人 / 控制 / AI 方向的實習與 Werkstudent",
    skillCat4: "機器學習 / AI",
    skillCat5: "開發工具",
    skillCat3: "方向",
    nowLabel: "近期",
    nowText: "正在學習 Computer Science 基礎、AI、Machine Learning、LLMs 與 Prompt Engineering。同時在做 AI 與自動化方向的個人項目。",
    skill1Title: "Robotics & Control",
    skill1Text: "ROS/ROS2、MATLAB、Simulink、OpenCV、控制系統與機器人仿真。",
    skill2Title: "Programming & Systems",
    skill2Text: "Python、C++、Linux、GitHub、數據處理與工程化腳本。",
    skill3Title: "AI & Automation",
    skill3Text: "AI、Machine Learning、PyTorch、LLMs、Prompt Engineering 與自動化項目。",
    languagesLabel: "語言",
    languagesTitle: "我會說的語言。",
    lang1Name: "中文",
    lang1Level: "母語",
    lang2Name: "德語",
    lang2Level: "C1",
    lang3Name: "英語",
    lang3Level: "B2",
    lang4Name: "日語",
    lang4Level: "≈ N4",
    projectsLabel: "實驗與項目",
    projectsTitle: "課程實驗與個人小項目。",
    demo1Title: "倒立擺-小車可視化",
    demo1Meta: "交互式 demo  ·  2025",
    demo1Text: "瀏覽器內可交互的倒立擺 + 小車系統仿真，可調質量、長度、阻尼等參數，實時觀察狀態變化與控制信號。",
    demo2Title: "平面 2R 機械臂仿真",
    demo2Meta: "交互式 demo  ·  2025",
    demo2Text: "二連桿平面機械臂仿真，可拖拽末端執行器，實時演示正向 / 逆向運動學解算。",
    demo3Title: "7 自由度機械臂仿真",
    demo3Meta: "交互式 demo  ·  2025",
    demo3Text: "瀏覽器中的 7 自由度機械臂可視化，可逐關節控制並觀察末端姿態變化，基於 DH 參數建模。",
    demo5Title: "RRT — 快速擴展隨機樹",
    demo5Meta: "Python 源碼  ·  2025",
    demo5Text: "基於隨機採樣的單向樹路徑規劃，tkinter 實時動畫展示樹擴展與避障，可對比不同參數下的結果。",
    demo6Title: "Bidirectional RRT",
    demo6Meta: "Python 源碼  ·  2025",
    demo6Text: "兩棵採樣樹分別從起點與終點同時生長，相遇即得通路。可視化展示兩樹擴展過程與最終拼接路徑。",
    demo7Title: "PRM — 概率路圖",
    demo7Meta: "Python 源碼  ·  2025",
    demo7Text: "對自由空間隨機採樣並構建近鄰圖，再用 Dijkstra 求最短無碰撞路徑。適合多次查詢的靜態場景。",
    project1Title: "MATLAB Laboratory Course",
    project1Timeline: "課程實驗  ·  WS 2025/26",
    project1Text:
      "內容：Static truss、Dynamic Crane、Measurement Data Analysis 和 Optimisation of the truss structure。實驗使用 MATLAB 完成結構力學建模、ODE 仿真、FFT 信號分析、符號計算和優化任務。",
    project2Title: "Automatic Control I Lab / Regelungstechnik I",
    project2Timeline: "課程實驗  ·  SS 2026",
    project2Text:
      "內容：實驗站點包括 Two Tank System、MATLAB 1、MATLAB 2、Rotary Arm、Active Suspension 和 Magnetic Levitation System。課程實驗圍繞自動控制基礎，將 Regelungstechnik A / dynamical systems and control 的理論用於建模、仿真、控制器設計和實驗觀察。",
    contactLabel: "聯繫我",
    followLabel: "關注我",
    contactTitle: "歡迎交流 Robotics、Control Systems、AI Tools 與 LLMs。",
    footerText: "© 2026 楊定帥.",
    footerSource: "源碼 ↗",
    footerUpdated: "更新於 2026-05-26",
    backToTop: "回到頂部"
  },
  ja: {
    documentTitle: "ディンシュアイ・ヤン | ロボティクス、制御工学、AI",
    metaDescription:
      "ディンシュアイ・ヤン の多言語個人サイト。ロボティクス、制御工学、メカトロニクス、AI、自動化プロジェクトを紹介します。",
    homeAria: "ホームに戻る",
    languageAria: "言語選択",
    actionsAria: "主な操作",
    profileAria: "個人情報の概要",
    brandMark: "DY",
    brandName: "ディンシュアイ・ヤン",
    navAbout: "私について",
    navEducation: "学歴",
    navSkills: "スキル",
    navProjects: "実験",
    navContact: "連絡先",
    introLine: "個人サイト",
    heroGreeting: "こんにちは、",
    heroName: "ディンシュアイ・ヤン",
    heroDomain1: "ロボティクス",
    heroDomain2: "制御工学",
    heroDomain3: "AI",
    heroTitle: "こんにちは、ディンシュアイ・ヤン です。ロボティクス、制御工学、AI に取り組んでいます。",
    heroText:
      "現在エアランゲンでメカトロニクスの修士課程に在籍。多くの時間を制御ループ、マニピュレータ、そしてそれらを賢くする AI ツールに費やしています。",
    viewProjects: "ラボを見る →",
    contactMe: "連絡する",
    profileTitle: "M.Sc. メカトロニクス  ·  2025 – 2027  ·  FAU",
    profileRole: "Friedrich-Alexander-Universität Erlangen-Nürnberg (FAU) · Erlangen, Germany",
    focusLabel: "関心分野",
    focusValue: "Robotics、Control Engineering、Computer Science、AI & LLMs",
    statusLabel: "現在学習中",
    statusValue: "Computer Science fundamentals、AI、Machine Learning、LLMs、Prompt Engineering",
    aboutLabel: "私について",
    aboutTitle: "材料工学からメカトロニクス、ロボティクス、AI へ。",
    aboutText1:
      "我本科学的是材料工程，但真正让我好奇的从来是那些机器本身——以及让它们变得智能的那些东西。看着人形机器人学会走路、抓取、像人一样推理，是把我拉进这个领域的根本原因。",
    aboutQuote: "ヒューマノイドロボットと身体性のある知能こそが未来だと信じています。",
    aboutText2:
      "だからメカトロニクスへ進路を変え、エアランゲンへ来ました — 制御ループ、マニピュレータ、そして現代の AI ツールを一つずつ学ぶために。それらがいつかどのキッチンにもどの工場にも現れる時、自分もその場にいたい。",
    educationLabel: "学歴",
    educationTitle: "学んだ場所。",
    edu1Degree: "M.Sc. メカトロニクス",
    edu1School: "Friedrich-Alexander-Universität Erlangen-Nürnberg (FAU) · ドイツ・エアランゲン",
    edu1Status: "在学中",
    edu2Degree: "工学士 · 材料成形・制御工学",
    edu2School: "広東工業大学 (GDUT) · 中国・広州",
    skillsLabel: "スキル",
    skillsTitle: "制御、ロボットソフトウェア、AI ツールをつなぐ実践的なスタック。",
    skillCat1: "言語",
    skillCat2: "ロボティクス & シミュ",
    factLocLabel: "拠点",
    factLocValue: "ドイツ・エアランゲン",
    factGradLabel: "卒業予定",
    factGradValue: "2027 年 4 月",
    factOpenLabel: "募集中",
    factOpenValue: "ロボティクス / 制御 / AI のインターン・Werkstudent",
    skillCat4: "ML & AI",
    skillCat5: "開発ツール",
    skillCat3: "領域",
    nowLabel: "現在",
    nowText: "Computer Science の基礎、AI、Machine Learning、LLMs、Prompt Engineering を学習中。AI と自動化分野の個人プロジェクトに取り組んでいます。",
    skill1Title: "Robotics & Control",
    skill1Text: "ROS/ROS2、MATLAB、Simulink、OpenCV、制御システム、ロボットシミュレーション。",
    skill2Title: "Programming & Systems",
    skill2Text: "Python、C++、Linux、GitHub、データ処理、エンジニアリングスクリプト。",
    skill3Title: "AI & Automation",
    skill3Text: "AI、Machine Learning、PyTorch、LLMs、Prompt Engineering、自動化プロジェクト。",
    languagesLabel: "言語",
    languagesTitle: "話せる言語。",
    lang1Name: "中国語",
    lang1Level: "母語",
    lang2Name: "ドイツ語",
    lang2Level: "C1",
    lang3Name: "英語",
    lang3Level: "B2",
    lang4Name: "日本語",
    lang4Level: "≈ N4",
    projectsLabel: "ラボと実験",
    projectsTitle: "授業のラボと自作の実験。",
    demo1Title: "振り子-台車ビジュアライザー",
    demo1Meta: "インタラクティブ demo  ·  2025",
    demo1Text: "ブラウザ内で動く倒立振り子と台車のシミュレーション。質量、長さ、減衰を調整しながら状態を観察。",
    demo2Title: "平面 2R ロボットシミュレータ",
    demo2Meta: "インタラクティブ demo  ·  2025",
    demo2Text: "2 リンクの平面マニピュレータ。エンドエフェクタをドラッグして順・逆運動学を体感。",
    demo3Title: "7-DOF ロボットアーム",
    demo3Meta: "インタラクティブ demo  ·  2025",
    demo3Text: "ブラウザ上の 7 自由度ロボットアーム。関節ごとの制御と DH モデリング。",
    demo5Title: "RRT — Rapidly-exploring Random Tree",
    demo5Meta: "Python ソース  ·  2025",
    demo5Text: "サンプリングに基づく単一ツリー経路計画。tkinter でツリーの成長と障害物回避をリアルタイムに可視化。",
    demo6Title: "Bidirectional RRT",
    demo6Meta: "Python ソース  ·  2025",
    demo6Text: "始点と終点から同時に成長する 2 本のツリーを接続して経路を生成。アニメーションで動作確認可能。",
    demo7Title: "PRM — 確率的ロードマップ",
    demo7Meta: "Python ソース  ·  2025",
    demo7Text: "自由空間のランダムサンプリングからグラフを構築し、Dijkstra で最短の衝突なし経路を探索。静的環境で多回クエリに有効。",
    project1Title: "MATLAB Laboratory Course",
    project1Timeline: "ラボ授業  ·  WS 2025/26",
    project1Text:
      "内容：Static truss、Dynamic Crane、Measurement Data Analysis、Optimisation of the truss structure。MATLAB を用いて構造力学モデリング、ODE シミュレーション、FFT 信号解析、記号計算、最適化を行いました。",
    project2Title: "Automatic Control I Lab / Regelungstechnik I",
    project2Timeline: "ラボ授業  ·  SS 2026",
    project2Text:
      "内容：実験ステーションは Two Tank System、MATLAB 1、MATLAB 2、Rotary Arm、Active Suspension、Magnetic Levitation System です。Regelungstechnik A / dynamical systems and control の基礎を、モデリング、シミュレーション、制御器設計、実験観察に応用しました。",
    contactLabel: "連絡する",
    followLabel: "フォローする",
    contactTitle: "Robotics、Control Systems、AI Tools、LLMs について気軽に連絡してください。",
    footerText: "© 2026 ディンシュアイ・ヤン.",
    footerSource: "ソース ↗",
    footerUpdated: "更新 2026-05-26",
    backToTop: "上に戻る"
  }
};

const languageMeta = {
  en: "en",
  de: "de",
  zh: "zh-CN",
  zhTw: "zh-TW",
  ja: "ja"
};

function getInitialLanguage() {
  const saved = localStorage.getItem("preferredLanguage");
  if (saved && translations[saved]) return saved;

  const browserLanguage = navigator.language.slice(0, 2).toLowerCase();
  return translations[browserLanguage] ? browserLanguage : "zh";
}

function applyLanguage(language) {
  const dictionary = translations[language] || translations.zh;
  document.documentElement.lang = languageMeta[language] || "zh-CN";
  document.title = dictionary.documentTitle;

  const description = document.querySelector('meta[name="description"]');
  if (description) description.setAttribute("content", dictionary.metaDescription);

  document.querySelectorAll("[data-i18n]").forEach((element) => {
    const key = element.dataset.i18n;
    if (dictionary[key]) element.textContent = dictionary[key];
  });

  document.querySelectorAll("[data-i18n-aria-label]").forEach((element) => {
    const key = element.dataset.i18nAriaLabel;
    if (dictionary[key]) element.setAttribute("aria-label", dictionary[key]);
  });

  document.querySelectorAll("[data-lang]").forEach((button) => {
    const isActive = button.dataset.lang === language;
    button.classList.toggle("is-active", isActive);
    button.setAttribute("aria-pressed", String(isActive));
  });

  localStorage.setItem("preferredLanguage", language);
}

document.querySelectorAll("[data-lang]").forEach((button) => {
  button.addEventListener("click", () => applyLanguage(button.dataset.lang));
});

applyLanguage(getInitialLanguage());

// Theme toggle
function getInitialTheme() {
  const saved = localStorage.getItem("theme");
  if (saved === "light" || saved === "dark") return saved;
  return window.matchMedia && window.matchMedia("(prefers-color-scheme: dark)").matches ? "dark" : "light";
}

function applyTheme(theme) {
  document.documentElement.setAttribute("data-theme", theme);
  localStorage.setItem("theme", theme);
}

document.querySelectorAll(".theme-toggle").forEach((btn) => {
  btn.addEventListener("click", () => {
    const next = document.documentElement.getAttribute("data-theme") === "dark" ? "light" : "dark";
    applyTheme(next);
  });
});

applyTheme(getInitialTheme());

// Scroll-triggered fade-in reveal
(function setupReveal() {
  const targets = document.querySelectorAll(
    ".hero-copy, .profile-panel, .section .section-heading, .section .text-block, .timeline-item, .skill-row, .language-row, .project-card, .now-section, .contact-section > div, .contact-right"
  );
  targets.forEach((el) => el.classList.add("reveal"));

  if (!("IntersectionObserver" in window)) {
    targets.forEach((el) => el.classList.add("is-visible"));
    return;
  }
  const obs = new IntersectionObserver(
    (entries) => {
      entries.forEach((entry) => {
        if (entry.isIntersecting) {
          entry.target.classList.add("is-visible");
          obs.unobserve(entry.target);
        }
      });
    },
    { threshold: 0.12, rootMargin: "0px 0px -40px 0px" }
  );
  targets.forEach((el) => obs.observe(el));
})();
